const LOTTERY_API = process.env.REACT_APP_LOTTERY_API as string;
const LOTTERY_DRAW_API = process.env.REACT_APP_LOTTERY_DRAW_API as string;
const LOTTERY_RESULTS_API = process.env.REACT_APP_LOTTERY_RESULTS_API as string;

export { LOTTERY_API, LOTTERY_DRAW_API, LOTTERY_RESULTS_API };
